apiVersion: v1
kind: Service
metadata:
  name: iris-model-ml-service
spec:
  selector:
    app: iris-model-ml-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
  type: LoadBalancer

