# This is a basic workflow to help you get started with Actions

name: CI Dev sanity test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "dev" branch
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test_model:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with: 
              python-version: "3.12"
      - name: Upgrade pip and build tools
        run: |
              python -m pip install --upgrade pip setuptools wheel
      - name: Install Dependencies
        run: 
              pip install -r requirements.txt
      - name: Pull data and model from dvc
        run:  |
              dvc pull
      - name: Run tests
        run:  |
              pytest --maxfail=1 --disable-warnings -q > results.txt
      - name: post CML Report
        env:  
              REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
        run:  |
              echo "## Test Report" > report.md
              cat results.txt >> report.md
              cml comment create report.md
